[package]
name = "rhostman"
version = "1.0.0"
authors = ["damjack <giacomello.damiano@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/damjack/rhostman"
repository = "https://github.com/damjack/rhostman"
keywords = ["cli", "hosts", "ads", "blocking"]
categories = ["command-line-utilities"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
nix = { version = "0.31.3", default-features = false, features = ["user", "fs"] }
reqwest = { version = "0.13.5", default-features = false, features = ["blocking", "rustls"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
thiserror = "2.0.20"

[dev-dependencies]
tempfile = "3"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
